# Generated by Django 3.0.7 on 2020-07-03 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200701_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumSide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_side_name', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composer_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conductor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('orchestra_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CountryOfProduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributor_name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenreOfRecording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_letter', models.CharField(blank=True, max_length=200, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecordingCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_company_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SizeName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VynilAudioType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_type_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['custom_id']},
        ),
        migrations.RemoveField(
            model_name='album',
            name='year_of_records',
        ),
        migrations.RemoveField(
            model_name='album',
            name='year_of_release',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quality',
        ),
        migrations.AddField(
            model_name='album',
            name='issue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='year_of_issue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='year_of_records_from',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='year_of_records_to',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='singer',
            name='singer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(blank=True, null=True)),
                ('size_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.SizeName')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='audio_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.VynilAudioType'),
        ),
        migrations.AddField(
            model_name='album',
            name='composer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Composer'),
        ),
        migrations.AddField(
            model_name='album',
            name='conductor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Conductor'),
        ),
        migrations.AddField(
            model_name='album',
            name='country_of_production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.CountryOfProduction'),
        ),
        migrations.AddField(
            model_name='album',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Distributor'),
        ),
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.GenreOfRecording'),
        ),
        migrations.AddField(
            model_name='album',
            name='quality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Quality'),
        ),
        migrations.AddField(
            model_name='album',
            name='recording_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.RecordingCompany'),
        ),
        migrations.AddField(
            model_name='album',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Size'),
        ),
        migrations.AddField(
            model_name='productdescription',
            name='composer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Composer'),
        ),
        migrations.AddField(
            model_name='track',
            name='album_side',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.AlbumSide'),
        ),
    ]
