# Generated by Django 3.0.7 on 2020-07-03 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200703_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdescription',
            name='conductor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Conductor'),
        ),
    ]
